ValeevGroup/SeQuant

SeQuant/core/op.hpp
SeQuant/core/wick.hpp
SeQuant/core/wick.impl.hpp
tests/unit/test_wick.cpp

this makes implementation of tensor form of Wick's theorem trivial

wick engine tries to maintain the original index pairings

---

SeQuant/domain/mbpt/models/cc.cpp
SeQuant/domain/mbpt/mr.cpp
SeQuant/domain/mbpt/mr.hpp
SeQuant/domain/mbpt/mr/op.impl.cpp
SeQuant/domain/mbpt/mr/op.impl.hpp
SeQuant/domain/mbpt/sr.cpp
SeQuant/domain/mbpt/sr.hpp
SeQuant/domain/mbpt/sr/op.impl.cpp
SeQuant/domain/mbpt/sr/op.impl.hpp
tests/unit/test_mbpt.cpp

- `Lambda()` functions in `mbpt::sr`, `mbpt::mr` and corresponding `op` namespaces renamed to `Λ()`
- Similar changes to perturbed Λ operators in #141

Rename Lambda() functions to Λ()

---

SeQuant/core/optimize/optimize.cpp
tests/unit/test_optimize.cpp

If the expression fed into the optimize function is a sum that contains an addend which is either a sum or a product itself, but only contains a single element (e.g. a single addend or a single factor), the visiting mechanism inside the cluster function would end up not visiting those terms and thereby preventing them from being processed (aka: they are swallowed and never see the light of day again).
A test case checking for the expected (non-swallowing) behavior is added as well.

Prevent optimize::reorder from swallowing terms

---

SeQuant/core/tensor.hpp
SeQuant/domain/mbpt/spin.cpp
SeQuant/domain/mbpt/spin.hpp
examples/srcc/srcc.cpp
tests/unit/test_parse_expr.cpp
tests/unit/test_spin.cpp
tests/unit/test_tensor.cpp

The closed_shell_CC_spintrace function would error if it was fed the CC energy equations, because it unconditionally performs a biorthogonal transform, which assumes the presence of external indices (aka: it assumes that we are dealing with a CC residual equation).
This commit changes the code so that we only perform the transformation for residuals, but skip it for energy expressions (fully contracted expressions).

Support energy expressions to be spintraced

---

SeQuant/core/space.hpp
SeQuant/domain/mbpt/convention.cpp
tests/unit/test_space.cpp

add complete_inactive_unoccupied space as a union of other_unoccupied and inactive_unoccupied for CT-F12 methods in MPQC

add complete_inactive_unoccupied space.

---

SeQuant/core/parse/parse.cpp

Unable to compile MPQC using SeQuant master using Clang 17.0.3 and Boost 1.83. This PR patches the issue.

Bugfix: MPQC Doesn't compile

---

SeQuant/core/expr.hpp
SeQuant/core/tensor.cpp
SeQuant/core/tensor.hpp
SeQuant/core/tensor_network.cpp
SeQuant/domain/mbpt/mr.cpp
SeQuant/domain/mbpt/op.cpp
SeQuant/domain/mbpt/op.hpp
SeQuant/domain/mbpt/op.ipp
SeQuant/domain/mbpt/sr.cpp
tests/unit/test_canonicalize.cpp
tests/unit/test_mbpt.cpp
tests/unit/test_tensor.cpp

This PR introduces the ability to distinguish objects (Tensor and mbpt::Operator) and their adjoints with labels. Unicode superscript character `⁺` (`U+207A`) is added as a suffix to the base label.

Feature: Distinguish adjoints with labels

---

SeQuant/domain/mbpt/mr.cpp
SeQuant/domain/mbpt/sr.cpp
examples/srcc/srcc.cpp

- `mbpt::{sr,mr}::Operator` use `optype2label` for labels
- Added checks for λ residual number of terms  in `srcc`

MBPT Misc Changes

---

SeQuant/core/hash.hpp
tests/unit/test_mbpt.cpp
tests/unit/test_tensor.cpp

Fix hash_value template resolution

---

SeQuant/core/expr.hpp
SeQuant/core/expr_fwd.hpp
SeQuant/core/meta.hpp
SeQuant/domain/eval/eval.hpp

The used enable-ifs looked a bit scary and have therefore been
refactored to use intermediates with (hopefully) clear names.
Furthermore, a couple of tests in those enable-ifs have been performed
with std::is_same, but only removing const from the compared type and
thus these checks would not work properly as soon as a reference type
was passed.
This could be observed while constructing a Product from a non-const
other product. Thus, the type of the to-be-copied object was just
Product & and not const Product &, which is what the copy-ctor
(correctly) is defined for. However, there is the templated
Product(Range &&) ctor, that thanks to the universal reference is the
more specialized candidate in this case (it takes the type as-is without
requiring a const to be slapped on). This would …

Revamp and fix enable-ifs in expr.cpp

---

.github/workflows/cmake.yml

Fixes #192 
`macos-latest` is now Sonoma and M1-based
- https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/
- https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

[ci] Fix macOS CI

---

SeQuant/core/rational.hpp

inlclude boost numeric cast header.

---

CMakeLists.txt
SeQuant/core/export/itf.cpp
SeQuant/core/export/itf.hpp
SeQuant/core/utility/indices.hpp
tests/unit/test_export.cpp
tests/unit/test_utilities.cpp

This commit implements functionality that allows to translate a SeQuant expression tree to executable ITF code. The assumption being that said expression tree has been factorized into a binary tree first.
The Integrated Tensor Framework (ITF) is a domain-specific language (DSL) for writing down tensor contractions. The code is interpreted by the Molpro quantum chemistry program package.
For more information see
H.-J. Werner et al., WIREs Comput. Mol. Sci., Vol. 2, No. 2 p. 242-253 (https://doi.org/10.1002/wcms.82)

Implement ITF translator

---

SeQuant/core/optimize/fusion.cpp
SeQuant/core/optimize/fusion.hpp
tests/unit/test_fusion.cpp

Eg.
- `1/2 AB + 1/4 AC = 1/4 A (2 B + C)`
- `- 1/2 AB - 1/4 AC = - 1/4 A (2 B + C)`
In the second example, the gcd is factored out, and -1 is factored out afterward as a canonicalization step.

Factor out the gcd of the scalars when two `Product` summands are fused.

---

SeQuant/core/context.cpp

The docs claim that this was already the case, but the implementation used a default constructed pointer (which is nullptr) instead of a pointer to a default-constructed registry.

Use a default-constructed IndexSpaceRegistry instead of nullptr

---

.github/workflows/cmake.yml

If a branch is updated, cancel in-progress workflows. 
See GitHub's [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#example-using-concurrency-and-the-default-behavior)

[CI] Cancel duplicate workflows

---

SeQuant/domain/mbpt/op.cpp
SeQuant/domain/mbpt/op.hpp
tests/unit/test_mbpt.cpp

I used $\theta$ for the label, other suggestions are welcome. 
- Minor change to `to_latex()` behaviour for Operator class: `to_latex(θ(1))` will produce $\theta_{1}$ instead of just $\theta$
- Unit tests

Introduce a general operator

---

SeQuant/core/eval_expr.cpp
tests/unit/test_eval_ta.cpp

Support for evaluating EOM IP/EA like expressions. Refactors the logic in `target_braket` and new evaluation unit tests.

Support evaluation of non-particle-conserving tensors

---

SeQuant/domain/mbpt/op.cpp
tests/unit/test_mbpt.cpp

- Bugfix in `A()` operators when one of the ranks is zero. 
- Added unit tests to make sure that screening in `op::vac_av` works properly.

Fix projection with zero ranks

---

SeQuant/domain/eval/eval.hpp

Fixes the issue reported in https://github.com/ValeevGroup/mpqc4/pull/521. Removes the extra `add_inplace()` call in `sequant::evaluate()`

Bugfix in `evaluate()`

---

SeQuant/core/tensor_network.cpp
SeQuant/core/tensor_network.hpp
SeQuant/core/tensor_network_v2.cpp
SeQuant/core/tensor_network_v2.hpp

The type of this member variable being the type that it was caused compiler warnings. Also, it turns out that there is no need for this index collection to be a member variable in the first place. It is only ever used very locally in the code. Hence, it has now been converted into a local variable instead. As a bonus, this gets rid of the compiler warning as the member variable it referred to no longer exists.
Note that not caching the index list should be fine as the functions it is being used in are almost never called repeatedly on the same TensorNetwork instance. Therefore, the caching benefit that the member variable provided is nullified.
Fixes #250

Get rid of grand_index_list_ member variable

---

CMakeLists.txt
SeQuant/core/algorithm.hpp
SeQuant/core/eval_expr.cpp
SeQuant/core/index.hpp
SeQuant/core/tensor_canonicalizer.hpp
SeQuant/core/tensor_network.cpp
SeQuant/core/tensor_network.hpp
SeQuant/core/tensor_network_v2.hpp
SeQuant/core/utility/swap.hpp
SeQuant/domain/mbpt/spin.cpp
cmake/modules/FindOrFetchGoogleBenchmark.cmake
tests/unit/test_canonicalize.cpp

example: `g{i1,i4;a1,a4}:A * t{a4;i4}` and `g{i3,i2;a2,a4}:A * t{a4;i3}` are equivalent up to a sign.

`TN::canonicalize_slots` produces phase associated with reordering antisymmetric bra/ket slots bundles

---

SeQuant/core/tensor_canonicalizer.cpp
tests/unit/test_spin.cpp
tests/unit/test_tensor_network.cpp

This reverts commit ba832da3054fc181fee88d7c45f627a5ea9f1ae7.
The reason being that Index::operator< is NOT the right way to compare indices in this context. If we also account for index labels (instead of only their space), we are comparing full indexed tensor elements rather than tensor blocks (slots) as this class is supposed to do.
In order for test cases to work with this re-introduced change, this commit also reverts
"amend tests for ba832da3054fc181fee88d7c45f627a5ea9f1ae7" (commit 4a9543851105e2bae0939495986351fe74930d70)
Finally, a hand full of additional test cases had to be adapted to the changed canonicalization routine.

Make TensorBlockIndexComparer compare tensor blocks (slots) again

---

SeQuant/core/math.hpp

Using a plain std::shared_ptr together with std::atomic_{load,store} has
been deprecated in C++20 and the API is removed in C++26. See P2869
(and/or https://github.com/cplusplus/papers/issues/1525) for details.
This commit removes the use of this depracted API in the way suggested
by P2869 (that is, wrap in a std::atomic type and use that directly
rather than via std::atomic_{load,store}).

Refactor deprecated use of shared_ptr atomic access API

---

SeQuant/core/eval_expr.cpp
tests/unit/test_eval_expr.cpp

More general version (as in: fix also works for variables and other leaf expressions) of #285

Fix scalar * tensor binarizing to tree with tensor as root

---

SeQuant/core/utility/indices.hpp
SeQuant/domain/mbpt/spin.cpp
tests/unit/test_spin.cpp

However, the question is: is it a desired feature for `spintrace` to be given a (seemingly) inconsistent set of external indices? 'cause there are some test cases that do this. I'm just not sure whether this is on purpose or not...
EDIT: This has been discussed and it's indeed the test cases that are faulty. Hence we'll keep the consistency check in place and fix the test cases.

Add ext index consistency check to spintrace()

---

cmake/modules/FindOrFetchGoogleBenchmark.cmake

As discussed in #312, `find_package` is not needed here, can directly use `VRGFindOrFetchPackage` module.

Drop `find_package` from FindOrFetchGoogleBenchmark

---

SeQuant/core/eval_expr.cpp
tests/unit/test_eval_expr.cpp

This is required instead of lazily computing them during binarization to avoid surprises. See the test cases.

Compute intermediate hashes strictly.

---

CMakeLists.txt
SeQuant/external/bliss/graph.cc
SeQuant/external/bliss/graph.hh

this saves on dynamic memory allocation. Most of our graphs will have vertices with relatively low order

use `boost::container::small_vector` for `bliss::{Graph,Digraph}::Vertex::edges*`

---

SeQuant/core/abstract_tensor.hpp
SeQuant/core/attr.hpp
SeQuant/core/context.cpp
SeQuant/core/context.hpp
SeQuant/core/index.hpp
SeQuant/core/op.hpp
SeQuant/core/optimize.hpp
SeQuant/core/tensor.hpp
SeQuant/core/tensor_canonicalizer.cpp
SeQuant/core/tensor_network/utils.hpp
SeQuant/core/tensor_network_v3.cpp
SeQuant/core/tensor_network_v3.hpp
SeQuant/core/wick.hpp
SeQuant/domain/mbpt/op.cpp
SeQuant/domain/mbpt/op.hpp
benchmarks/main.cpp
tests/integration/eomcc.cpp
tests/integration/eval/btas/main.cpp
tests/integration/eval/ta/main.cpp
tests/integration/osstcc.cpp
tests/integration/srcc.cpp
tests/integration/stcc.cpp
tests/integration/stcc_rigorous.cpp
tests/unit/test_canonicalize.cpp
tests/unit/test_main.cpp
tests/unit/test_runtime.cpp
tests/unit/test_tensor_network.cpp
tests/unit/test_wick.cpp
utilities/external-interface/external_interface.cpp
utilities/tensor_network_graphs.cpp

this is implemented just like support for canonicalization of slots (bra and ket introduced in v3) and braket slot bundles (in v2). Need to introduce vertices for bra and ket slot bundles and swap them if needed. Currently we don't have the support for conjugation as canonicalization biproduct, but I think tensors already have the support for conjugation. For real tensors straight swap is enough.

TNV3: support for `BraKetSymmetry`
