- tests/unit/catch.hpp
This is the latest release of Catch v2. It contains a fix for MINSIGSTKSZ no longer being a constant expressions.
Fixes #94
> [test]: Update Catch to v2.13.9

- SeQuant/core/clone_packed.cpp
- SeQuant/core/eval_node.hpp
- SeQuant/core/expr.hpp
- SeQuant/core/expr_operator.hpp
- SeQuant/core/optimize.hpp
- SeQuant/core/parse/parse_expr.cpp
- SeQuant/domain/mbpt/spin.cpp
- tests/unit/test_clone_packed.cpp
- tests/unit/test_eval_node.cpp
- tests/unit/test_expr.cpp
> {Sum,Product}::{append,prepend} need to clone the arguments

- SeQuant/core/expr.hpp
- SeQuant/core/latex.hpp
- SeQuant/core/rational.hpp
- SeQuant/core/wolfram.hpp
- SeQuant/core/wstring.hpp
- tests/unit/test_expr.cpp
- tests/unit/test_main.cpp
- tests/unit/test_math.cpp
> Use multiprecision for `Constant` 

- CMakeLists.txt
- SeQuant/core/eval_node.hpp
- SeQuant/core/index.hpp
- SeQuant/core/meta.hpp
- SeQuant/core/space.hpp
- SeQuant/core/utility/string.hpp
- SeQuant/domain/eval/eval.hpp
- SeQuant/domain/eval/eval_result.hpp
- SeQuant/domain/mbpt/spin.cpp
- SeQuant/domain/mbpt/spin.hpp
- examples/stcc_rigorous/stcc_rigorous.cpp
- tests/unit/test_eval_btas.cpp
- tests/unit/test_index.cpp
- tests/unit/test_spin.cpp
such as those appearing in CSV-CC methods (PNO-CCSD, etc.)
> support for spintracing expressions with protoindices

- SeQuant/domain/mbpt/mr.cpp
- SeQuant/domain/mbpt/mr.hpp
- SeQuant/domain/mbpt/sr.cpp
- SeQuant/domain/mbpt/sr.hpp
- tests/unit/test_mbpt.cpp
active space is above fermi level in closed-Fock picture
also adds MR screening unit tests
> fix mr qn `combine` logic

- CMakeLists.txt
- cmake/modules/FindOrFetchLibPerm.cmake
- external/versions.cmake
As requested, here the FetchContent integration of https://github.com/Krzmbrzl/libPerm
> Add libPerm FetchContent

- CMakeLists.txt
- SeQuant/core/index.hpp
- SeQuant/core/index_space_registry.hpp
- SeQuant/core/meta.hpp
- examples/synopsis/synopsis6.cpp
> build fixes for c++17

- SeQuant/domain/mbpt/op.cpp
Tested in MPQC and all validation tests passed.
> Bugfix in perturbed T and Λ ops

- SeQuant/core/parse/deparse.cpp
Fix a minor formatting issue:)
> Fix clang-format

- SeQuant/core/expr.cpp
- SeQuant/core/expr_algorithm.hpp
- SeQuant/core/tensor_network.cpp
- SeQuant/core/utility/singleton.hpp
- SeQuant/core/wick.hpp
- SeQuant/core/wick.impl.hpp
- SeQuant/domain/eval/eval.hpp
- SeQuant/domain/eval/eval_result.cpp
- SeQuant/domain/eval/eval_result.hpp
- SeQuant/domain/mbpt/op.cpp
- cmake/modules/FindOrFetchRangeV3.cmake
- examples/srcc/srcc.cpp
- tests/unit/test_main.cpp
- tests/unit/test_mbpt_cc.cpp
- tests/unit/test_utilities.cpp
- `Singleton::get_instance*` -> `Singleton::instance*`
- to manage lifetime API not returns `shared_ptr` instead of raw handles
- `Singleton::instance()` is safe to call from multiple threads even if `Singleton::set_instance` had not been called
> `Singleton` is thread-safe

- SeQuant/core/expr.cpp
- SeQuant/core/expr_algorithm.hpp
- SeQuant/core/tensor_network.cpp
- SeQuant/core/utility/singleton.hpp
- SeQuant/core/wick.hpp
- SeQuant/core/wick.impl.hpp
- SeQuant/domain/mbpt/op.cpp
- examples/srcc/srcc.cpp
- tests/unit/test_main.cpp
- tests/unit/test_utilities.cpp
https://github.com/ValeevGroup/SeQuant/pull/222#issuecomment-2218120202
> Singleton::instance() returns ref

- .github/workflows/docs.yml
- README.md
Use the correct license, and update the docs workflow name.
> Fix badges in README

- SeQuant/core/tensor.hpp
- external/versions.cmake
- tests/unit/test_eval_node.cpp
- tests/unit/test_mbpt.cpp
> Generalize printing of antisymm Tensors

- README.md
- SeQuant/domain/mbpt/vac_av.hpp
Some misc changes related to https://github.com/ValeevGroup/mpqc4/pull/528
> Misc Changes related to `mbpt::op`

- SeQuant/core/logger.hpp
- SeQuant/domain/eval/eval.hpp
- SeQuant/domain/eval/eval_result.cpp
- SeQuant/domain/eval/eval_result.hpp
setting Logger::eval::stream to null is now also OK
> reorg Logger's eval fields

- CMakeLists.txt
- INSTALL.md
- SeQuant/core/logger.hpp
- SeQuant/domain/eval/eval.hpp
- SeQuant/domain/eval/eval_result.cpp
- SeQuant/domain/eval/eval_result.hpp
amends https://github.com/ValeevGroup/SeQuant/pull/277
> disable eval tracing by default even if configured with `SEQUANT_EVAL_TRACE=ON`

- doc/examples/user/getting_started/ccd_pedestrian.cpp
- doc/user/getting_started/operators.rst
Updates code snippets in operators documentation
> docs: Fixup #292

- CMakeLists.txt
- INSTALL.md
- SeQuant/core/context.cpp
- SeQuant/core/context.hpp
- doc/user/getting_started/installing.rst
this produces significant speedup ... @ajay-mk please check
Most apps will want to do this anyway (good idea to initialize context a priori and manipulate from main thread only)
> Can disable thread-safety of context manipulation

- SeQuant/core/eval_expr.cpp
- tests/unit/test_eval_node.cpp
in the future will want to deduce the symmetry and/or project onto appropriate irreps
resolves #347
> [eval] tensor products are deduced to be asymmetric in all respects

- CMakeLists.txt
- SeQuant/core/bitset.hpp
- SeQuant/core/index.hpp
- SeQuant/core/index_space_registry.cpp
- SeQuant/core/index_space_registry.hpp
- SeQuant/core/space.cpp
- SeQuant/core/space.hpp
- SeQuant/core/utility/string.hpp
- SeQuant/core/wstring.hpp
- SeQuant/domain/mbpt/space_qns.hpp
- tests/unit/test_space.cpp
added ISR use example from the paper as a unit test
> `IndexSpaceRegistry` cleanup + paper example

- SeQuant/core/expressions/abstract_tensor.hpp
- SeQuant/core/expressions/expr_algorithms.cpp
- SeQuant/core/expressions/expr_algorithms.hpp
- SeQuant/core/expressions/product.hpp
- SeQuant/domain/mbpt/op.hpp
- tests/unit/test_expr.cpp
`flatten` flattens sums of sums and products of products
> introduce `flatten`

- SeQuant/core/index_space_registry.hpp
- tests/unit/test_space.cpp
- tests/unit/test_wick.cpp
return false if result is null
> fixup `ISR::valid_intersection`
